export enum Role {
    SUPER_ADMIN = 'ADMIN_USER',
    AGENT = 'AGENT_USER',
    USER = 'ROLE_USER',
    BRANCH_MAKER = 'CREATEUR_SUCCURSALE',
    BRANCH_CHECKER = 'VÉRIFICATEUR_SUCCURSALE',
    REGULATORY_MAKER = 'CREATEUR_RÉGLEMENTAIRE',
    REGULATORY_CHECKER = 'VÉRIFICATEUR_RÉGLEMENTAIRE'
  }
  